name: Anguler Docker Deploy
on:
  push:
    branches:
      - main

jobs:
  call:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}
      node_versions: '["22","24"]'
      push: true
      tags: '["latest"]'

  deploy_staging:
    name: Deploy to production server
    runs-on: ubuntu-latest
    needs: build_and_push
    environment:
      name: production
      url: https://production.example.com
    steps:
      - name: Deploy to Production Server
        env:
          ENV_LABEL: ${{ secrets.PRODUCTION_LABEL }}
          IMAGE_TAG: sha-${{github.sha}}

        run: |
          echo "Deploying to production server..."
      # docker container run -d -p 8080:8080 -e APP_ENVIRONMENT="$ENV_LABEL" ${{env.REGISTRY}}/${{env}}
